name: hudson_platecrane_module
services:
  sciclops:
    container_name: sciclops
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:${PROJECT_VERSION}
        - ${IMAGE}:dev
    command: python -m sciclops_rest_node --port 2000 --device ${DEVICE}
    privileged: true
    env_file: .env
    volumes:
      - /dev:/dev
      - ./src:/home/app/hudson_platecrane_module/src
      - ./tests:/home/app/hudson_platecrane_module/tests
    ports:
      - 2000:2000
