name: hudson_platecrane_module
services:
  hudson_platecrane_module:
    container_name: hudson_platecrane_module
    image: ghcr.io/ad-sdl/hudson_platecrane_module
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/hudson_platecrane_module:latest
        - ghcr.io/ad-sdl/hudson_platecrane_module:dev
    command: python -m sciclops_rest_node --port 2000 --device ${DEVICE}
    privileged: true
    env_file: .env
    volumes:
      - /dev:/dev
      - ./src:/home/madsci/hudson_platecrane_module/src
      - ./tests:/home/madsci/hudson_platecrane_module/tests
    network_mode: host
    restart: unless-stopped
